@echo off
echo Stopping and removing old containers...
docker-compose down

echo Building new image...
docker-compose build

echo Starting new containers...
docker-compose up -d

echo Showing logs...
docker-compose logs -f
